### ISSUE TITLE
Error when attempting to train

### ISSUE THREAD

**Issue by dillfrescott** [TylorShine/MNP-SVC#1]
```python
 [DDSP Model] Minimum-Phase harmonic Source Combtooth Subtractive Synthesiser
Traceback (most recent call last):
  File "C:\Users\cross\Downloads\MNP-SVC\train.py", line 48, in <module>
    model = CombSubMinimumNoisedPhase(
  File "C:\Users\cross\Downloads\MNP-SVC\modules\vocoder.py", line 191, in __init__
    self.register_buffer("use_add_noise_env", torch.tensor(use_add_noise_env))
RuntimeError: Could not infer dtype of NoneType
```

**Comment by jreoka** [comment]
It fixes it if i comment out this line https://github.com/TylorShine/MNP-SVC/blob/284409e681b33ef93cb35fdf74335d99f55af28b/modules/vocoder.py#L191

But I have no idea if that will break the entire result or not

**Comment by jreoka** [comment]
Yeah that breaks the inference. I'm lost as to what to do.

**Comment by TylorShine** [comment]
Thanks for your report and So sorry for late reply. I didn't think the versioning, because I thought this repo is for researching...!
But I planning to versioning to this repo. I have already updated the repo to v2. You can update it and use it if you want!
